import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const welcomeMessages = [
      {
        languageName: "Hindi",
        message: "नमस्ते",
        alternateEnglishText: "Namaste",
      },
    { languageName: "French", message: "Bienvenue" },
    { languageName: "Italian", message: "Benvenuto/a" },
    { languageName: "Portuguese", message: "Bem-vindo/a" },
    { languageName: "Swedish", message: "Välkommen" },
    // { languageName: "Punjabi", message: "Sata Sri Akal" },
    // { languageName: "Bangla", message: "Nomoshkar" },
    {
      languageName: "Kashmiri",
      message: "आदाब",
      alternateEnglishText: "Aadab",
    },
    { languageName: "Magadhi", message: "Parnam" },
    { languageName: "Marathi", message: "Namaskar" },
    { languageName: "Tamil", message: "Vanakkam" },
    { languageName: "Telegu", message: "Namaskaram" },
    { languageName: "Dari", message: "Salâm" },
    { languageName: "Dholuo", message: "Ajolo in" },
    { languageName: "Kannada", message: "ಸ್ವಾಗತಾರ್ಹ" },
    { languageName: "Japanese", message: "ようこそ" },
    { languageName: "Kimeru", message: "igua wamukiri mono" },
    { languageName: "Hausa", message: "maraba" },
    { languageName: "Kinyarwanda", message: "Ikaze" },
    { languageName: "Chichewa", message: "takulandirani" },
    {
      languageName: "Punjabi",
      message: "ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ",
      alternateEnglishText: "Sat Sri kal",
    },
    {
      languageName: "Bangla",
      message: "নমস্কার",
      alternateEnglishText: "Nomoshkar",
    },
    {
      languageName: "Magadhi",
      message: "प्रणाम",
      alternateEnglishText: "Parnam",
    },
    {
      languageName: "Marathi",
      message: "नमस्कार",
      alternateEnglishText: "Namaskar",
    },
    {
      languageName: "Tamil ",
      message: "வணக்கம்",
      alternateEnglishText: "Vanakkam ",
    },
    {
      languageName: "Telegu",
      message: "నమస్కరం",
      alternateEnglishText: "Namaskaram ",
    },
    {
      languageName: "BrajBhasha",
      message: "राधे राधे",
      alternateEnglishText: "Radhe Radhe ",
    },
  ];
  const [welcomeIndex, setWelcomeIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setWelcomeIndex((prevIndex) => (prevIndex + 1) % welcomeMessages.length);
    }, 3000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className="d-flex-cc">
            <div style={{display:"flex", gap:"1rem" ,flexWrap:"wrap"}}>
            <span className={styles.fadeIn}>
        <h1 className={styles.title} >
            {welcomeMessages[welcomeIndex].message}
        </h1>
            <br/>in<br/>
            <i>{welcomeMessages[welcomeIndex].languageName}</i>
          </span>
          <div>
          <div class="blobs">
  <div class="blob"></div>
  <div class="blob"></div>
  <div class="blob"></div>
  <div class="blob"></div>
  <div class="blob"></div>
</div>
          </div>
                </div>
          </div>

        </main>
        <footer><p>Powered by navneet</p>
      </footer>
    </div>
  );
}